### ISSUE TITLE
[interview] 2020-06-30

### ISSUE THREAD

**Issue by Alice52** [Alice52/java-ocean#123]
#### 1. language

1. spring
2. spring boot
3. spring annotation
4. spring cloud
5. mybatis
6. mybatis-plus
7. jpa
8. spring-data

#### 2. db
1. mysql: index
2. nosql

   - mongo
   - redis: cluster
         - 击穿: 大量访问`不存在的Key`， 导致的数据库查询
         - 穿透: 由于Key的失效, 而且`大并发`下访问导致的数据库查询
         - 雪崩: 大量的`key同时失效,` 导致的数据库查询
         - 分布式锁

3. [sql server](https://github.com/Alice52/java-ocean/files/4855517/SQL.txt)

#### 3. mq

1. active mq
2. rabbit mq
3. rocket mq
4. ~~kafaka~~

#### 4. java

1. jvm
2. juc
3. java8
4. **enum**
5. io
6. generic
7. collection + map
8. reflect + proxy

#### 5. job

1. quartz
2. ~~elastic job~~
3. spring task

#### 7. 分布式

1. 事务
2. 锁
3. 框架

#### ~~8. rpc~~
1. [rpc](https://www.bilibili.com/video/BV1eE411T7GC)
2. netty 

#### 10. 密码学基础

---

#### 11. common

1. [git-link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
2. maven
3. rest
4. oauth2.0

    - [jd](https://docs.jdcloud.com/cn/ias/oauth2-service)
    - [开放平台](https://shimo.im/doc/NrIu4eiaKbEHzKYQ)
        - code: redirect_uri 需要和 app 创建时的一样: 为了不会被篡改回调到奇怪的地方
        - token: app client_id + secret + code
        - userinfo: access_token
        - revocation
        - introspection

5. jmter
6. docker
7. ELK
    - elastic search
    - logstash
    - kibana
8. linux

**Comment by Alice52** [comment]
### project experience 

#### 1. off-line: 
#### 2. tax-tool
#### 3. esb 

1. component
2.  intergration

#### 4. kol promot

**Comment by Alice52** [comment]
## time prioed

1. from: 

- [ ] 2018-07-09 ~ 2019-03-02
- [x] 2019-07-01 ~  

2. to: until this issue close

## introduce

1. first job 
2. grateful for this company: `augmentum`

**Comment by Alice52** [comment]
> ### project experience
> #### 1. off-line:
> #### 2. tax-tool
> #### 3. esb
> 1. component
> 2. intergration
> 
> #### 4. kol promot

---
the follow project is not belong to company experience

1. 电商
2. 秒杀
3. 支付

**Comment by Alice52** [comment]
#124

**Comment by Alice52** [comment]
## 需要复习的技能点

- [ ] 1. rest + json

  - restful
  - jackson

- [ ] 2. common

  - git / svn
  - maven
  - jmeter
  - oauth
  - tools: `map-struct, hutool, just-auth`
  - cicd: `travis/jenkins`

- [ ] 3. java-se

  - basic: `io + class-loader + serialize + static + this`
  - generic
  - enum
  - reflect
  - inner-class
  - interface
  - collection + map
  - java8: `optional + stream + map + functional + lambda + date`
  - juc + jvm

- [ ] 4. java-ee

  - spring
  - spring mvc
  - spring boot
  - spring annotation
  - spring cloud
  - spring validation
  - _spring data_
  - mybatis
  - ~~mybatis-plus~~

- [ ] 5. database

  - mysql: `syntax + optimzie`
  - monogo
  - redis: cluster
  - _sqlserver: sp_

- [ ] 6. linux
- [ ] 7. nginx
- [ ] 8. docker

  - docker
  - docker-compose
  - docker-file

- [ ] 9. mq

  - active-mq
  - rabbit-mq
  - _rocket-mq_

- [ ] 10. job

  - quartz
  - ~~elastic job~~
  - spring schedule

* [ ] 11. design-patterns

  - 单例模式
  - 工厂模式
  - 策略模式
  - ~~代理模式~~
  - ~~构建者模式~~
  - ~~适配器模式~~

- [ ] 12. language

  - php
  - .netcore

- [ ] 13. ~~rpc~~

  - ~~grpc~~
  - ~~netty~~

* [ ] 14. 了解 `工作流`

  - _wso2-bps_
  - _activiti_

- [ ] 15. _wso2_

  - esb/ei
  - is
  - bps
  - dss

**Comment by Alice52** [comment]
# version-2

## review list

### common

- [ ] 1. rest + http
- [ ] 2. json: jackson
- [ ] 3. oauth: open platform
- [ ] 4. jmeter + jmh
- [ ] 5. nginx
- [ ] 6. coding style + new-tech

### java se

- [ ] 1. io
- [ ] 2. collection + map
- [ ] 3. enum
- [ ] 4. interface + abstract + inner class + exception
- [ ] 5. reflect + proxy
- [ ] 6. generic
- [ ] 7. java8: `stream + lambda + optional + functional + LocalDateTime`
- [ ] 8. agent
- [ ] 9. jvm
- [ ] 10. juc

### java ee

- [ ] 1. mybatis

  - flow: `factory + session + prestatement + result`
  - cache + handler-plugin

- [ ] 2. spring

  - spring ioc
  - spring bean lifecycle
  - spring autowire + resource + inject
  - spring profile
  - spring property
  - spring aop: `transactional + aspect-aop`

- [ ] 3. spring mvc

  - flow: `mvc handler mapping flow`
  - validation
  - sync

- [ ] 4. spring boot

  - boot starer
  - boot exception strategy
  - boot log

- [ ] 5. spring cloud

### db

- [ ] 1. mysql

  - syntax
  - optimize: `index+guideline`
  - sm + cluster

- [ ] 2. redis

  - common config: `durable + data-struct`
  - cache + distribution[redission]
  - sm + cluster
  - interview
  - redission + jedis

- [ ] 3. mongodb

  - common usage

### job

- [ ] 1. quartz

### rpc

- [ ] 1. grpc

### mq

- [ ] 1. rabbit-mq
- [ ] 2. ~~rocket-mq~~
- [ ] 3. active-mq

### linux

- [ ] 1. docker

   - docker
   - docker-compose
   - docker-file

- [ ] 2. ci/cd + travis + github-action
- [ ] 3. common command

### design-patterns

- [ ] 1. 单例模式
- [ ] 2. 工厂模式
- [ ] 3. 策略模式
- [ ] 4. 代理模式
- [ ] 5. 构建者模式
- [ ] 6. 适配器模式

**Comment by Alice52** [comment]
## todo list

1. 准备好简历
2. 刷笔试题: leetcode
3. 准备项目经验: 2 - 3
    - 这个需要使用到下面的这些技术: 选型, 使用场景
4. 项目中遇到的问题： 3 - 4
5. 看面试大全:
   - java 基础: jvm + juc + collection + map + reflect + proxy
   - mysql 优化
   - redis
   - quartz: 源码
   - mq: rabbitmq
   - docker

**Comment by Alice52** [comment]
## list

1. 推断构造函数

**Comment by Alice52** [comment]
## core-core
1. jvm
2. juc
3. collection
---
4. spring framework
5. redis
6. mysql
7. mq
8. quartz

9. coding
10. design-model
11. design-system

**Comment by Alice52** [comment]
#159

**Comment by Alice52** [comment]
## Schedule

|  type  | clock |
| :----: | :---: |
| Get Up | 07:00 |
| Lunch  | 11:30 |
| Break  | 13:00 |
| Dinner | 19:00 |
| Sleep  | 22:00 |

**Comment by Alice52** [comment]
## TODO LIST

### java-se

1. juc
    - [ ] [CountDownLatch](https://www.cnblogs.com/leesf456/p/5406191.html)
    - [ ] [CyclicBarrier](https://www.cnblogs.com/leesf456/p/5392816.html)
    - [ ] [Semaphore](https://www.cnblogs.com/leesf456/p/5414778.html)

**Comment by Alice52** [comment]
AES

**Comment by Alice52** [comment]
aes

**Comment by Alice52** [comment]
```txt
##  rabbitmq 的顺序消费问题

### 需求

1. 一张 TABLE 的所有消息必须严格的顺序消费: create -- update(casino lifecycle) -- delete
2. 但是不同 TABLE 的消息没有顺序要求

### queue 的使用[手动 ack]

1. 手动 ack:
    - auto 导致消息由于业务异常, 服务宕机导致丢失
    - pre-fetch-count: 消息的预读

2. 拆分多个 queue[都对应一个log表]
    - table.lifecycle: to them
    - table.configuration: to us
    - table.rating: 
    - table.message
    - table.FillCredit
    - table.BuyIn
    - Patron
    - NNChipRol
    - Program
    - Employee
    - ...

3. 此时如果每个 queue 都只有一个 consumer, 则不会出现顺序问题: 最终的方案是 producer: [seqNo(int)(tableId作为key在头中) + ack], 
    
    - 消费时的业务异常, 没有必要重试[就是逻辑不对]
    - 但是由于网络引起的消费的 ack 失败会导致消息的~~重复消费~~[ack与logic变成事务的/通过sql-unique解决], unack 之后 requeue 会导致**顺序消费的问题**[这个问题不需要解决:运维在做]
        - 会记录第三方的消息内容log表[防止争议], 与 ack 在一个事务内可以解决重复消费问题
    - 如果要解决顺序消费问题: **需要消息身上自带 seqNo 或者带有上一条消息的 msg-id**[可以部署多个 consumer]
        - 发送端需要设置 seqNo[last-msg-id] + xxl-job 补发[插入数据库和发送是事务的]
        - 在消费端消费本消息之前如果是 seqNo=1[last-msg-id = null] 则直接消费
        - 如果 seqNo - 1 [last-msg-id] 已经被消费[数据库], 就直接消费[注意事务问题]
        - 否则会直接 requeue
```
