### ISSUE TITLE
[interview] 2020-06-30 TODO LIST

### ISSUE THREAD

**Issue by Alice52** [Alice52/java-ocean#124]
- [ ] 1. 微信收藏全部整理一遍
- [ ] 2. java-ocean 重新整理一遍
- [ ] 3. [interview 视频第二期](https://www.bilibili.com/video/BV18b411M7xz)
- [ ] 4. RPC
- [ ] 5. 面试题
- [ ] 6. project

**Comment by Alice52** [comment]
#123

**Comment by Alice52** [comment]
## java se

- [ ] 1. aqs
- [ ] 2. jdk7: hashMap & ConcurrentHashMap
- [ ] 2. jdk8: hashMap & ConcurrentHashMap
- [ ] 3. ThreadLocal
- [ ] 4. CountDownLatch
- [ ] 5. CyclicBarrier
- [ ] 6. Semaphore
- [ ] 7. 面试题

## middle-ware

- [ ] 1. redis - 布隆过滤器
- [ ] 2. redis - redis 跳表
- [ ] 4. redis - zset限流: https://www.jianshu.com/p/95f7a165b29b
- [ ] 5. mysql - 间隙表
- [ ] 6. mysql - 慢查询

## framework

- [ ] 1. spring ioc
- [ ] 2. spring aop: transaction/log/validator
- [ ] 3. spring boot 自动配置原理
- [ ] 4. spring mvc 请求流程
- [ ] 5. spring exception 源码解读

## project

- [ ] 1. sso 过程
- [ ] 2. oss 使用方法

## algorithms

- [ ] 1. 排序算法
- [ ] 2. 红黑树
- [ ] 3. b/b+树
- [ ] 4. redis - LRU/LFU
- [ ] 5. 雪花算法
- [ ] 6. 常见的算法题(剑指offer)

**Comment by Alice52** [comment]
https://www.cnblogs.com/grey-wolf/p/13034371.html

**Comment by Alice52** [comment]
- [ ] 1. LRU 算法实现
